# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kevin Keomanee-Dizon
tagline:          'biophysicist'
description:      'Biophysics and Quantitaive Bioimaging'
url:              https://kdizon.github.io/

author:
  name:           'Kevin Keomanee-Dizon'
  url:            https://twitter.com/kevinkeomanee
