# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-seo-tag

# Setup
title:            Kevin Keomanee-Dizon
tagline:          'Biophysicist'
description:      'Alfred E. Mann Doctoral Fellow at the University of Southern California'
url:              https://kdizon.github.io/

author:
  name:           'Kevin Keomanee-Dizon'
  url:            https://twitter.com/kevinkeomanee
